### ISSUE TITLE
AWS scylla_io_setup fails

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-operator#102]
```
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
tuning /sys/devices/pci0000:00/0000:00:1e.0/nvme/nvme0/nvme0n1
tuning: /sys/devices/pci0000:00/0000:00:1e.0/nvme/nvme0/nvme0n1/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:1e.0/nvme/nvme0/nvme0n1/queue/nomerges to 2

ERROR:root:/var/lib/scylla/commitlog was not found. Please check the configuration and run scylla_io_setup again.

failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 17, in <module>
    setup.io()
  File "/scyllasetup.py", line 53, in io
    self._run(['/opt/scylladb/scripts/scylla_io_setup'])
  File "/scyllasetup.py", line 32, in _run
    subprocess.check_call(*args, **kwargs)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_io_setup']' returned non-zero exit status 1.
```

**Comment by mmatczuk** [comment]
In 4.0.0 works

**Comment by enaydanov** [comment]
It may caused by too low `fs.aio-max-nr` value. Default 65536 is not enough to run Scylla under Docker.
