### ISSUE TITLE
Flake: Scylla Manager integration [It] should discover cluster and sync tasks

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-operator#1231]
https://github.com/scylladb/scylla-operator/actions/runs/4885577292/jobs/8729441531?pr=1230
[e2e-artifacts-parallel-alpha.tar.lz4.zip](https://github.com/scylladb/scylla-operator/files/11404414/e2e-artifacts-parallel-alpha.tar.lz4.zip)
[logs_13091.zip](https://github.com/scylladb/scylla-operator/files/11404415/logs_13091.zip)

```
[FAILED] [576.223 seconds]
I0505 05:42:08.396946       1 tests/tests_run.go:418] "Process finished" ID=6 Command="/usr/bin/scylla-operator-tests run scylla-operator/conformance/parallel --loglevel=2 --artifacts-dir=/home/runner/work/_temp/e2e-artifacts --flake-attempts=0 --timeout=60m --feature-gates=AllAlpha=true,AllBeta=true --override-ingress-address=10.96.88.229 --parallel-server-address=127.0.0.1:45553 --loglevel=0 --parallel-shard=6" ProcessState="exit status 1"
Scylla Manager integration [It] should discover cluster and sync tasks
I0505 05:42:08.398194       1 tests/tests_run.go:418] "Process finished" ID=13 Command="/usr/bin/scylla-operator-tests run scylla-operator/conformance/parallel --loglevel=2 --artifacts-dir=/home/runner/work/_temp/e2e-artifacts --flake-attempts=0 --timeout=60m --feature-gates=AllAlpha=true,AllBeta=true --override-ingress-address=10.96.88.229 --parallel-server-address=127.0.0.1:45553 --loglevel=0 --parallel-shard=13" ProcessState="exit status 0"
github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:23
I0505 05:42:08.398992       1 tests/tests_run.go:418] "Process finished" ID=10 Command="/usr/bin/scylla-operator-tests run scylla-operator/conformance/parallel --loglevel=2 --artifacts-dir=/home/runner/work/_temp/e2e-artifacts --flake-attempts=0 --timeout=60m --feature-gates=AllAlpha=true,AllBeta=true --override-ingress-address=10.96.88.229 --parallel-server-address=127.0.0.1:45553 --loglevel=0 --parallel-shard=10" ProcessState="exit status 0"

  Timeline >>
  STEP: Creating a new namespace @ 05/05/23 05:32:32.164
  May  5 05:32:32.271: INFO: Created namespace "e2e-test-scyllacluster-pt9kd-n5b2q".
  STEP: Waiting for service account token Secret "e2e-user-token" in namespace "e2e-test-scyllacluster-pt9kd-n5b2q". @ 05/05/23 05:32:32.419
  STEP: Waiting for default ServiceAccount in namespace "e2e-test-scyllacluster-pt9kd-n5b2q". @ 05/05/23 05:32:32.614
  STEP: Creating a ScyllaCluster @ 05/05/23 05:32:33.32
  STEP: Waiting for the ScyllaCluster to rollout (RV=6022) @ 05/05/23 05:32:33.676
  May  5 05:37:04.268: INFO: ScyllaCluster e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6 (RV=8031) is rolled out
  STEP: Verifying the ScyllaCluster @ 05/05/23 05:37:09.286
  May  5 05:37:09.372: INFO: Found 1 pvc(s) in namespace "e2e-test-scyllacluster-pt9kd-n5b2q"
  May  5 05:37:09.372: INFO: Found 1 pvc(s) for ScyllaCluster "e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6"
  STEP: Waiting for the ScyllaCluster to reach consistency ALL @ 05/05/23 05:37:09.385
  May  5 05:37:09.597: INFO: ScyllaDB nodes have reached status consistency.
  STEP: Inserting data @ 05/05/23 05:37:09.597
  May  5 05:37:09.597: INFO: Creating CQL session (hosts="10.103.123.180")
  May  5 05:37:09.661: INFO: Creating keyspace "sjmcz2gt" with RF 1
  May  5 05:37:09.997: INFO: Creating table "sjmcz2gt"."test"
  May  5 05:37:10.400: INFO: Inserting data into table "sjmcz2gt"."test"
  May  5 05:37:10.452: INFO: Awaiting schema agreement
  May  5 05:37:10.454: INFO: Schema agreement reached
  STEP: Verifying the data @ 05/05/23 05:37:10.466
  May  5 05:37:10.466: INFO: Reading data from table "sjmcz2gt"."test"
  STEP: Waiting for the cluster sync with Scylla Manager @ 05/05/23 05:37:10.469
  [FAILED] in [It] - github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:88 @ 05/05/23 05:41:10.473
  STEP: Collecting events from namespace "e2e-test-scyllacluster-pt9kd-n5b2q". @ 05/05/23 05:41:10.473
  STEP: Found 33 events. @ 05/05/23 05:41:10.49
  May  5 05:41:10.490: INFO: At 2023-05-05 05:32:33 +0000 UTC - event for basic-8dmv6-member: {scyllacluster-controller } ServiceAccountCreated: ServiceAccount e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6-member created
  May  5 05:41:10.490: INFO: At 2023-05-05 05:32:34 +0000 UTC - event for basic-8dmv6-auth-token: {scyllacluster-controller } SecretCreated: Secret e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6-auth-token created
  May  5 05:41:10.490: INFO: At 2023-05-05 05:32:34 +0000 UTC - event for basic-8dmv6-member: {scyllacluster-controller } RoleBindingCreated: RoleBinding e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6-member created
  May  5 05:41:10.490: INFO: At 2023-05-05 05:32:43 +0000 UTC - event for basic-8dmv6-local-client-ca: {scyllacluster-controller } SecretCreated: Secret e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6-local-client-ca created
  May  5 05:41:10.490: INFO: At 2023-05-05 05:32:43 +0000 UTC - event for basic-8dmv6-local-client-ca: {scyllacluster-controller } ConfigMapCreated: ConfigMap e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6-local-client-ca created
  May  5 05:41:10.490: INFO: At 2023-05-05 05:32:54 +0000 UTC - event for basic-8dmv6-local-user-admin: {scyllacluster-controller } SecretCreated: Secret e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6-local-user-admin created
  May  5 05:41:10.490: INFO: At 2023-05-05 05:32:57 +0000 UTC - event for basic-8dmv6-local-serving-ca: {scyllacluster-controller } SecretCreated: Secret e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6-local-serving-ca created
  May  5 05:41:10.490: INFO: At 2023-05-05 05:32:57 +0000 UTC - event for basic-8dmv6-local-serving-ca: {scyllacluster-controller } ConfigMapCreated: ConfigMap e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6-local-serving-ca created
  May  5 05:41:10.490: INFO: At 2023-05-05 05:32:59 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a: {scyllacluster-controller } StatefulSetCreated: StatefulSet e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6-us-east-1-us-east-1a created
  May  5 05:41:10.490: INFO: At 2023-05-05 05:32:59 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a: {statefulset-controller } SuccessfulCreate: create Claim data-basic-8dmv6-us-east-1-us-east-1a-0 Pod basic-8dmv6-us-east-1-us-east-1a-0 in StatefulSet basic-8dmv6-us-east-1-us-east-1a success
  May  5 05:41:10.490: INFO: At 2023-05-05 05:32:59 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a: {statefulset-controller } SuccessfulCreate: create Pod basic-8dmv6-us-east-1-us-east-1a-0 in StatefulSet basic-8dmv6-us-east-1-us-east-1a successful
  May  5 05:41:10.490: INFO: At 2023-05-05 05:32:59 +0000 UTC - event for data-basic-8dmv6-us-east-1-us-east-1a-0: {persistentvolume-controller } WaitForFirstConsumer: waiting for first consumer to be created before binding
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:00 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a-0: {default-scheduler } Scheduled: Successfully assigned e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6-us-east-1-us-east-1a-0 to fv-az339-828
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:03 +0000 UTC - event for nodeconfig-podinfo-8ec14afa-4174-4f48-adcc-79ca58b12bfa: {NodeConfigCM-controller } ConfigMapCreated: ConfigMap e2e-test-scyllacluster-pt9kd-n5b2q/nodeconfig-podinfo-8ec14afa-4174-4f48-adcc-79ca58b12bfa created
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:04 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a-0: {kubelet fv-az339-828} FailedMount: MountVolume.SetUp failed for volume "scylladb-serving-certs" : secret "basic-8dmv6-local-serving-certs" not found
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:09 +0000 UTC - event for basic-8dmv6: {scyllacluster-controller } PodDisruptionBudgetCreated: PodDisruptionBudget e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6 created
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:09 +0000 UTC - event for basic-8dmv6-client: {scyllacluster-controller } ServiceCreated: Service e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6-client created
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:09 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a-0: {scyllacluster-controller } ServiceCreated: Service e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6-us-east-1-us-east-1a-0 created
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:10 +0000 UTC - event for basic-8dmv6-local-cql-connection-configs-admin: {scyllacluster-controller } SecretCreated: Secret e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6-local-cql-connection-configs-admin created
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:10 +0000 UTC - event for basic-8dmv6-local-serving-certs: {scyllacluster-controller } SecretCreated: Secret e2e-test-scyllacluster-pt9kd-n5b2q/basic-8dmv6-local-serving-certs created
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:18 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Pulled: Container image "docker.io/scylladb/scylla-operator:ci" already present on machine
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:20 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Created: Created container sidecar-injection
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:21 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Started: Started container sidecar-injection
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:38 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Pulled: Container image "docker.io/scylladb/scylla:5.0.5" already present on machine
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:41 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Created: Created container scylla
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:45 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Pulled: Container image "docker.io/scylladb/scylla-manager-agent:3.0.1" already present on machine
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:45 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Started: Started container scylla
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:51 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Created: Created container scylla-manager-agent
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:54 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Started: Started container scylla-manager-agent
  May  5 05:41:10.490: INFO: At 2023-05-05 05:33:56 +0000 UTC - event for nodeconfig-podinfo-8ec14afa-4174-4f48-adcc-79ca58b12bfa: {NodeConfigCM-controller } ConfigMapUpdated: ConfigMap e2e-test-scyllacluster-pt9kd-n5b2q/nodeconfig-podinfo-8ec14afa-4174-4f48-adcc-79ca58b12bfa updated
  May  5 05:41:10.490: INFO: At 2023-05-05 05:34:04 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Unhealthy: Startup probe failed: Get "http://10.85.0.57:8080/healthz": dial tcp 10.85.0.57:8080: connect: connection refused
  May  5 05:41:10.490: INFO: At 2023-05-05 05:34:16 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Unhealthy: Readiness probe failed: HTTP probe failed with statuscode: 503
  May  5 05:41:10.490: INFO: At 2023-05-05 05:35:29 +0000 UTC - event for basic-8dmv6-us-east-1-us-east-1a-0: {kubelet fv-az339-828} Unhealthy: Liveness probe failed: Get "http://10.85.0.57:8080/healthz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  STEP: Collecting dumps from namespace "e2e-test-scyllacluster-pt9kd-n5b2q". @ 05/05/23 05:41:10.49
  STEP: Destroying namespace "e2e-test-scyllacluster-pt9kd-n5b2q". @ 05/05/23 05:41:10.712
  STEP: Waiting for namespace "e2e-test-scyllacluster-pt9kd-n5b2q" to be removed. @ 05/05/23 05:41:10.715
  << Timeline

  [FAILED] Unexpected error:
      <*errors.errorString | 0xc0002f7510>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  occurred
  In [It] at: github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:88 @ 05/05/23 05:41:10.473

  Full Stack Trace
    github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.glob..func16.1()
    	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:88 +0x8e4
```

**Comment by zimnx** [comment]
Failed 5 times in a row: 
https://github.com/scylladb/scylla-operator/actions/runs/5101179834/jobs/9169896510

[e2e-artifacts-parallel-alpha.tar.lz4 (22).zip](https://github.com/scylladb/scylla-operator/files/11592455/e2e-artifacts-parallel-alpha.tar.lz4.22.zip)

**Comment by tnozicka** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1257/pull-scylla-operator-e2e-gke-parallel/1694361199220625408#1:test-build-log.txt%3A2161
```
 • [FAILED] [778.504 seconds]
Scylla Manager integration [It] should discover cluster and sync tasks
github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:23 
...
   [FAILED] Unexpected error:
      <wait.errInterrupted>: 
      timed out waiting for the condition
      {
          cause: <*errors.errorString | 0xc000357590>{
              s: "timed out waiting for the condition",
          },
      }
  occurred
  In [It] at: github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:88 @ 08/23/23 15:13:25.819
  Full Stack Trace
    github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.glob..func17.1()
    	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:88 +0x8e4 
```

**Comment by tnozicka** [comment]
this is flaking a lot and a most common flake these days, we need to prioritize fixing it

**Comment by rzetelskik** [comment]
Did we have any progress with it in previous attempts? I recall this has already been worked on.

**Comment by rzetelskik** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1346/pull-scylla-operator-e2e-gke-parallel/1694725730631421952#1:test-build-log.txt%3A1105

```
• [FAILED] [459.897 seconds]
Scylla Manager integration [It] should discover cluster and sync tasks
github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:23
...
  [FAILED] Unexpected error:
      <wait.errInterrupted>: 
      timed out waiting for the condition
      {
          cause: <*errors.errorString | 0xc00039af60>{
              s: "timed out waiting for the condition",
          },
      }
  occurred
  In [It] at: github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:88 @ 08/24/23 15:22:20.341
  Full Stack Trace
    github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster.glob..func17.1()
    	github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:88 +0x8e4
```

**Comment by rzetelskik** [comment]
> Failed 5 times in a row:
> https://github.com/scylladb/scylla-operator/actions/runs/5101179834/jobs/9169896510
> 
> [e2e-artifacts-parallel-alpha.tar.lz4 (22).zip](https://github.com/scylladb/scylla-operator/files/11592455/e2e-artifacts-parallel-alpha.tar.lz4.22.zip)

Missing ScyllaCluster manifests, Pod logs don't show anything unusual.


> https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1257/pull-scylla-operator-e2e-gke-parallel/1694361199220625408#1:test-build-log.txt%3A2161

Missing e2e artifacts.

Waiting for it to reproduce again with e2e artifacts.

**Comment by rzetelskik** [comment]
I went through logs of the most recent flaky run - https://github.com/scylladb/scylla-operator/issues/1231#issuecomment-1698070544. It looks like the flakiness happens due to a too low value of aio-max-nr in our CI.

```
$ cat artifacts/e2e-namespaces/e2e-test-scyllacluster-txwmf-h5j57/core_v1/pods/basic-ftt9m-us-east-1-us-east-1a-0/scylla.previous

2023-08-29T14:24:37.651284533Z FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/
O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr.
Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-29T14:24:37.655114283Z E0829 14:24:37.655025       1 sidecar/controller.go:143] syncing key 'e2e-test-scyllacl
uster-txwmf-h5j57/basic-ftt9m-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can'
t get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp 127.0.0.1:10000: connect: connection
 refused
2023-08-29T14:24:38.659237390Z 2023-08-29 14:24:38,652 INFO success: scylla entered RUNNING state, process has stayed
up for > than 1 seconds (startsecs)
2023-08-29T14:24:38.659253240Z 2023-08-29 14:24:38,652 INFO exited: scylla (exit status 7; not expected)
2023-08-29T14:24:39.666964897Z 2023-08-29 14:24:39,654 INFO spawned: 'scylla' with pid 96
2023-08-29T14:24:39.778456978Z FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/
O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr.
Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-29T14:24:40.746553836Z E0829 14:24:40.746442       1 sidecar/probes.go:154] "healthz probe: can't connect to S
cylla API" err="Get \"http://localhost/system/uptime_ms\": dial tcp 127.0.0.1:10000: connect: connection refused" Serv
ice="e2e-test-scyllacluster-txwmf-h5j57/basic-ftt9m-us-east-1-us-east-1a-0"
2023-08-29T14:24:40.780850056Z 2023-08-29 14:24:40,780 INFO success: scylla entered RUNNING state, process has stayed
up for > than 1 seconds (startsecs)
2023-08-29T14:24:40.832845983Z 2023-08-29 14:24:40,832 INFO exited: scylla (exit status 7; not expected)
2023-08-29T14:24:41.231561029Z Traceback (most recent call last):
2023-08-29T14:24:41.233341749Z 2023-08-29 14:24:41,231 INFO spawned: 'scylla' with pid 118
2023-08-29T14:24:41.236295918Z   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 196, in <module>
2023-08-29T14:24:41.236329758Z     args.func(args)
2023-08-29T14:24:41.236335828Z   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 122, in check_version
2023-08-29T14:24:41.236339858Z     current_version = sanitize_version(get_api('/storage_service/scylla_release_version
'))
2023-08-29T14:24:41.236343948Z   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 80, in get_api
2023-08-29T14:24:41.236357048Z     return get_json_from_url("http://" + api_address + path)
2023-08-29T14:24:41.236360978Z   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 75, in get_json_from_u
rl
2023-08-29T14:24:41.236364688Z     raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
2023-08-29T14:24:41.236369088Z RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_vers
ion" due to the following error: <urlopen error [Errno 99] Cannot assign requested address>
2023-08-29T14:24:41.382412010Z FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/
O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr.
Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-29T14:24:42.381561870Z 2023-08-29 14:24:42,381 INFO success: scylla entered RUNNING state, process has stayed
up for > than 1 seconds (startsecs)
2023-08-29T14:24:42.381821980Z 2023-08-29 14:24:42,381 INFO exited: scylla (exit status 7; not expected)
```

The failure of ScyllaDB container causes the scylla-manager agent to fail liveness probes:

```
$ cat artifacts/e2e-namespaces/e2e-test-scyllacluster-txwmf-h5j57/core_v1/pods/basic-ftt9m-us-east-1-us-east-1a-0/scylla-manager-agent.previous

2023-08-29T14:30:46.314497399Z STARTUP ERROR: server init: no connection to Scylla API, make sure that Scylla server is running and api_address and api_port are set correctly in config file [/etc/scylla-manager-agent/scylla-manager-agent.yaml /mnt/scylla-agent-config/scylla-manager-agent.yaml /mnt/scylla-agent-config/auth-token.yaml]: giving up after 60 attempts: dial tcp 0.0.0.0:10000: connect: connection refused
```

and only start much later, probably when some of the other parallel tests finish and let the ScyllaDB get up:
```
$ cat artifacts/e2e-namespaces/e2e-test-scyllacluster-txwmf-h5j57/core_v1/pods/basic-ftt9m-us-east-1-us-east-1a-0/scylla-manager-agent.current

2023-08-29T14:31:18.625850226Z {"L":"INFO","T":"2023-08-29T14:31:18.625Z","M":"Service started","_trace_id":"h64Z4fKVRSWLfKgaaRZugg"}
```

During that time, the manager controller repeatedly fails to register the cluster with ScyllaDB Manager:

```
$ cat artifacts/e2e-namespaces/scylla-manager/pods/scylla-manager-controller-c4bd7b47f-jv4sg/scylla-manager-controller.current

...
I0829 14:31:35.194846       1 manager/controller.go:199] "Enqueuing object" Operation="Update" GVK="scylla.scylladb.com/v1, Kind=ScyllaCluster" Ref="e2e-test-scyllacluster-txwmf-h5j57/basic-ftt9m" UID="51fae4ea-dc76-4147-80bb-917f1cd874cf"
I0829 14:31:35.194888       1 manager/sync.go:93] "Started syncing ScyllaCluster" ScyllaCluster="e2e-test-scyllacluster-txwmf-h5j57/basic-ftt9m" startTime="2023-08-29 14:31:35.19487545 +0000 UTC m=+560.548308248"
I0829 14:31:35.197181       1 manager/sync.go:134] "Executing action" action="add cluster \"\""
E0829 14:31:35.201056       1 manager/sync.go:137] "Failed to execute action" err="[POST /clusters][500] PostClusters default  &{Message:create cluster: status: dial tcp 10.68.7.9:10001: connect: connection refused - make sure the IP is correct and access to port 10001 is unblocked TraceID:JffJs4fRRZirxZR_0NmulQ}" action="add cluster \"\""
I0829 14:31:35.201127       1 manager/sync.go:95] "Finished syncing ScyllaCluster" ScyllaCluster="e2e-test-scyllacluster-txwmf-h5j57/basic-ftt9m" duration="6.245389ms"
E0829 14:31:35.201144       1 manager/controller.go:150] syncing key 'e2e-test-scyllacluster-txwmf-h5j57/basic-ftt9m' failed: [POST /clusters][500] PostClusters default  &{Message:create cluster: status: dial tcp 10.68.7.9:10001: connect: connection refused - make sure the IP is correct and access to port 10001 is unblocked TraceID:JffJs4fRRZirxZR_0NmulQ}
```

And only succeeds much later:

```
$ cat artifacts/e2e-namespaces/scylla-manager/pods/scylla-manager-controller-c4bd7b47f-jv4sg/scylla-manager-controller.current

...
I0829 14:36:05.705556       1 manager/controller.go:199] "Enqueuing object" Operation="Update" GVK="scylla.scylladb.com
/v1, Kind=ScyllaCluster" Ref="e2e-test-scyllacluster-kjrll-fn4wk/basic-q62b9" UID="2c3aa7a2-5cdb-4cbc-b129-fe1d18bbea09
"
I0829 14:36:05.705599       1 manager/sync.go:93] "Started syncing ScyllaCluster" ScyllaCluster="e2e-test-scyllacluster
-kjrll-fn4wk/basic-q62b9" startTime="2023-08-29 14:36:05.705587447 +0000 UTC m=+831.059020245"
I0829 14:36:05.714910       1 manager/sync.go:95] "Finished syncing ScyllaCluster" ScyllaCluster="e2e-test-scyllacluste
r-kjrll-fn4wk/basic-q62b9" duration="9.313979ms"
I0829 14:36:06.561691       1 manager/controller.go:199] "Enqueuing object" Operation="Update" GVK="scylla.scylladb.com
/v1, Kind=ScyllaCluster" Ref="e2e-test-scyllacluster-txwmf-h5j57/basic-ftt9m" UID="51fae4ea-dc76-4147-80bb-917f1cd874cf"
I0829 14:36:06.561723       1 manager/sync.go:93] "Started syncing ScyllaCluster" ScyllaCluster="e2e-test-scyllacluster-txwmf-h5j57/basic-ftt9m" startTime="2023-08-29 14:36:06.561714425 +0000 UTC m=+831.915147223"
I0829 14:36:06.564100       1 manager/sync.go:134] "Executing action" action="add cluster \"\""
I0829 14:36:06.579804       1 manager/sync.go:144] "Updating cluster status"...
```

```
$ cat artifacts/namespaces/scylla-manager/pods/scylla-manager-6df8b4dfc5-sqqjp/scylla-manager.current

{"L":"INFO","T":"2023-08-29T14:36:06.619Z","N":"cluster","M":"Adding new cluster","cluster_id":"eb73f925-ea08-4417-90fa-3b4512eac58f","_trace_id":"5FcpMJ5FTz6ZwAy5poZR2g"}
{"L":"INFO","T":"2023-08-29T14:36:06.624Z","N":"cluster.client","M":"Checking hosts connectivity","hosts":["10.68.13.9"],"_trace_id":"5FcpMJ5FTz6ZwAy5poZR2g"}
{"L":"INFO","T":"2023-08-29T14:36:06.625Z","N":"cluster.client","M":"Host check OK","host":"10.68.13.9","_trace_id":"5FcpMJ5FTz6ZwAy5poZR2g"}
{"L":"INFO","T":"2023-08-29T14:36:06.625Z","N":"cluster.client","M":"Done checking hosts connectivity","_trace_id":"5FcpMJ5FTz6ZwAy5poZR2g"}
{"L":"INFO","T":"2023-08-29T14:36:06.625Z","N":"cluster","M":"Cluster added","cluster_id":"eb73f925-ea08-4417-90fa-3b4512eac58f","_trace_id":"5FcpMJ5FTz6ZwAy5poZR2g"}
```

Which only happens a couple of seconds after the test has already timed out:
```
  STEP: Waiting for the cluster sync with Scylla Manager @ 08/29/23 14:32:00.685
push_pin
  [FAILED] in [It] - github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:88 @ 08/29/23 14:36:00.686
  ```
  
  Therefore I believe the tests itself is not flaky, but the entire CI is suffering from too few allowable concurrent requests with the current number of parallel tests allowed to run. The question is how to increase that number - resuming the efforts started in https://github.com/scylladb/scylla-operator/pull/887 seems like a right way to go.


@zimnx thanks for your help in debugging this!

**Comment by rzetelskik** [comment]
https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1371/pull-scylla-operator-e2e-gke-parallel/1699056438023819264

Hit it again, looks like the same reason behind the failure.

**Comment by tnozicka** [comment]
Nice catch, both of you. Yep, we need sysctl tuning, but in the short run - can you hardcode a value high enough for GKE into CICM? (https://cloud.google.com/kubernetes-engine/docs/how-to/node-system-config#using_a_node_system_configuration)

**Comment by rzetelskik** [comment]
Looks like fs.aio-max-nr is not supported in `linuxConfig.sysctl`: https://cloud.google.com/kubernetes-engine/docs/how-to/node-system-config#sysctl-options, https://github.com/googleapis/google-api-go-client/blob/62d88ff7c06b828324b3cf5fd004cdf75838f496/container/v1/container-gen.go#L3475, so we would need a dedicated DaemonSet either way?

**Comment by tnozicka** [comment]
ok, let's do a temporary daemonset in the setup script and linked issue to remove it with sysctl epic
