### ISSUE TITLE
SNI connectivity gets broken after operator upgrade

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#1286]
**Describe the bug**
After upgrade of the scylla-operator from the `1.8.1` version to the `1.9.0-rc.1` the SNI connectivity doesn't work anymore to the Scylla pods:

```
2023-06-23 08:37:59,802 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-06-23 08:37:59.799: (InfoEvent Severity.NORMAL) period_type=not-set event_id=8e0dd8df-dedb-49a6-8f24-1c9f65aedde5: message=Step8 - Verify data in the Scylla cluster
2023-06-23 08:37:59,812 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-06-23 08:37:59.800: (InfoEvent Severity.NORMAL) period_type=not-set event_id=6352f98f-1fc5-444d-ad0d-4fe7b6172a3a: message=Run some Queries to verify data after operator upgrade and scylla member addition
2023-06-23 08:37:59,847 f:cluster.py      l:3383 c:cassandra.cluster    p:WARNING > Cluster.__init__ called with contact_points specified, but no load_balancing_policy. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = [<SniEndPoint: a3b15b98bc5e145c2b3f85870b985cac-100374478.eu-north-1.elb.amazonaws.com:9142:cql.sct-cluster.sct.scylladb.com>], lbp = None)
2023-06-23 08:37:59,864 f:cluster.py      l:3390 c:cassandra.cluster    p:WARNING > [control connection] Error connecting to a3b15b98bc5e145c2b3f85870b985cac-100374478.eu-north-1.elb.amazonaws.com:9142:cql.sct-cluster.sct.scylladb.com: < t:2023-06-23 08:37:59,864 f:cluster.py      l:3390 c:cassandra.cluster    p:WARNING > [control connection] Error connecting to a3b15b98bc5e145c2b3f85870b985cac-100374478.eu-north-1.elb.amazonaws.com:9142:cql.sct-cluster.sct.scylladb.com:
2023-06-23 08:37:59,864 f:cluster.py      l:3390 c:cassandra.cluster    p:WARNING > Traceback (most recent call last):
2023-06-23 08:37:59,864 f:cluster.py      l:3390 c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 3606, in cassandra.cluster.ControlConnection._reconnect_internal
2023-06-23 08:37:59,864 f:cluster.py      l:3390 c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 3628, in cassandra.cluster.ControlConnection._try_connect
2023-06-23 08:37:59,864 f:cluster.py      l:3390 c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 1686, in cassandra.cluster.Cluster.connection_factory
2023-06-23 08:37:59,864 f:cluster.py      l:3390 c:cassandra.cluster    p:WARNING >   File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
2023-06-23 08:37:59,864 f:cluster.py      l:3390 c:cassandra.cluster    p:WARNING >   File "/usr/local/lib/python3.10/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
2023-06-23 08:37:59,864 f:cluster.py      l:3390 c:cassandra.cluster    p:WARNING >     self._connect_socket()
2023-06-23 08:37:59,864 f:cluster.py      l:3390 c:cassandra.cluster    p:WARNING >   File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
2023-06-23 08:37:59,864 f:cluster.py      l:3390 c:cassandra.cluster    p:WARNING > OSError: [Errno 8] Tried connecting to [('13.49.200.202', 9142)]. Last error: EOF occurred in violation of protocol (_ssl.c:997)
2023-06-23 08:37:59,865 f:cluster.py      l:3390 c:cassandra.cluster    p:ERROR > Control connection failed to connect, shutting down Cluster: < t:2023-06-23 08:37:59,865 f:cluster.py      l:3390 c:cassandra.cluster    p:ERROR > Control connection failed to connect, shutting down Cluster:
2023-06-23 08:37:59,865 f:cluster.py      l:3390 c:cassandra.cluster    p:ERROR > Traceback (most recent call last):
2023-06-23 08:37:59,865 f:cluster.py      l:3390 c:cassandra.cluster    p:ERROR >   File "cassandra/cluster.py", line 1756, in cassandra.cluster.Cluster.connect
2023-06-23 08:37:59,865 f:cluster.py      l:3390 c:cassandra.cluster    p:ERROR >   File "cassandra/cluster.py", line 3572, in cassandra.cluster.ControlConnection.connect
2023-06-23 08:37:59,865 f:cluster.py      l:3390 c:cassandra.cluster    p:ERROR >   File "cassandra/cluster.py", line 3617, in cassandra.cluster.ControlConnection._reconnect_internal
2023-06-23 08:37:59,865 f:cluster.py      l:3390 c:cassandra.cluster    p:ERROR > cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'a3b15b98bc5e145c2b3f85870b985cac-100374478.eu-north-1.elb.amazonaws.com:9142:cql.sct-cluster.sct.scylladb.com': OSError(8, "Tried connecting to [('13.49.200.202', 9142)]. Last error: EOF occurred in violation of protocol (_ssl.c:997)")})
```

All new connections fail this way.

**To Reproduce**
1. Deploy ingress controller
2. Deploy scylla-operator `1.8.1`
3. Deploy a 3-member Scylla cluster
4. Interact with Scylla using SNI
5. Upgrade the scylla-operator to `1.9.0-rc.1`
6. Interact with Scylla using SNI
7. See error

**Expected behavior**
The SNI connectivity must work before and after scylla-operator upgrade.

**Logs**
- **db-cluster-b80aba03.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b80aba03-682d-4f44-ab20-4ea6909e3d77/20230623_085041/db-cluster-b80aba03.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b80aba03-682d-4f44-ab20-4ea6909e3d77/20230623_085041/db-cluster-b80aba03.tar.gz)
- **sct-runner-events-b80aba03.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b80aba03-682d-4f44-ab20-4ea6909e3d77/20230623_085041/sct-runner-events-b80aba03.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b80aba03-682d-4f44-ab20-4ea6909e3d77/20230623_085041/sct-runner-events-b80aba03.tar.gz)
- **sct-b80aba03.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b80aba03-682d-4f44-ab20-4ea6909e3d77/20230623_085041/sct-b80aba03.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b80aba03-682d-4f44-ab20-4ea6909e3d77/20230623_085041/sct-b80aba03.log.tar.gz)
- **monitor-set-b80aba03.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b80aba03-682d-4f44-ab20-4ea6909e3d77/20230623_085041/monitor-set-b80aba03.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b80aba03-682d-4f44-ab20-4ea6909e3d77/20230623_085041/monitor-set-b80aba03.tar.gz)
- **loader-set-b80aba03.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b80aba03-682d-4f44-ab20-4ea6909e3d77/20230623_085041/loader-set-b80aba03.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b80aba03-682d-4f44-ab20-4ea6909e3d77/20230623_085041/loader-set-b80aba03.tar.gz)
- **kubernetes-b80aba03.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b80aba03-682d-4f44-ab20-4ea6909e3d77/20230623_085041/kubernetes-b80aba03.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b80aba03-682d-4f44-ab20-4ea6909e3d77/20230623_085041/kubernetes-b80aba03.tar.gz)
- [Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-1.9/job/upgrade/job/upgrade-operator-k8s-eks/9/)
- [Argus](https://argus.scylladb.com/test/249eff1c-7d50-40d5-94d7-daf663067610/runs?additionalRuns[]=b80aba03-682d-4f44-ab20-4ea6909e3d77)

**Environment:**
 - Platform: EKS
 - Kubernetes version: v1.25.10-eks-c12679a
 - Scylla version: 2022.2.9
 - Scylla-operator version: `1.8.1` -> `1.9.0-rc.1`

**Comment by zimnx** [comment]
` "--feature-gates=AutomaticTLSCertificates=true" ` flag in operator deployment got lost during upgrade, resulting in TLS being disabled leading to EOF.
