### ISSUE TITLE
Cluster won't get created if developerMode is set to false

### ISSUE THREAD

**Issue by ETisREAL** [scylladb/scylla-operator#1626]
### What happened?

Hi :) I am trying to move our cluster to production, however setting off the developerMode ends up in an infinite crash for the cluster.

I have installed the operator with helm specifying these configurations:
``` yaml
image:
  tag: latest

# Change log level
logLevel: 2

# Resources allocated to Scylla Operator pods
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 32Mi
```

and this is the helm chart values for the cluster:
``` yaml
scyllaImage:
  tag: 5.2.11
agentImage:
  tag: 3.1.2

# Cluster information
developerMode: false

datacenter: europe-west3-a
racks:
- name: rack0
  members: 1
  storage:
    capacity: 5Gi
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
```

### What did you expect to happen?

If I leave developerMode on, then everything starts up as normal, however when I trun it off I get these errors on the cluster side:
```
ERROR:root:Filesystem at /var/lib/scylla/data has only 5177327616 bytes available; that is less than the recommended 10 GB. Please free up space and run scylla_io_setup again.

failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 27, in <module>
    setup.io()
  File "/scyllasetup.py", line 68, in io
    self._run(['/opt/scylladb/scripts/scylla_io_setup'])
  File "/scyllasetup.py", line 38, in _run
    subprocess.check_call(*args, **kwargs)
  File "/opt/scylladb/python3/lib64/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_io_setup']' returned non-zero exit status 1.
E1210 17:58:42.098646       1 sidecar/controller.go:143] syncing key 'scylla/scylla-europe-west3-a-rack0-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp 127.0.0.1:10000: connect: connection refused
E1210 17:58:47.219548       1 sidecar/controller.go:143] syncing key 'scylla/scylla-europe-west3-a-rack0-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp 127.0.0.1:10000: connect: connection refused
E1210 17:58:47.245750       1 sidecar/probes.go:154] "healthz probe: can't connect to Scylla API" err="Get \"http://localhost/system/uptime_ms\": dial tcp 127.0.0.1:10000: connect: connection refused" Service="scylla/scylla-europe-west3-a-rack0-0"
E1210 17:58:57.246595       1 sidecar/probes.go:154] "healthz probe: can't connect to Scylla API" err="Get \"http://localhost/system/uptime_ms\": dial tcp 127.0.0.1:10000: connect: connection refused" Service="scylla/scylla-europe-west3-a-rack0-0"
E1210 17:58:57.460929       1 sidecar/controller.go:143] syncing key 'scylla/scylla-europe-west3-a-rack0-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp 127.0.0.1:10000: connect: connection refused
E1210 17:59:06.638659       1 sidecar/controller.go:143] syncing key 'scylla/scylla-europe-west3-a-rack0-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp 127.0.0.1:10000: connect: connection refused
E1210 17:59:07.246893       1 sidecar/probes.go:154] "healthz probe: can't connect to Scylla API" err="Get \"http://localhost/system/uptime_ms\": dial tcp 127.0.0.1:10000: connect: connection refused" Service="scylla/scylla-europe-west3-a-rack0-0"
E1210 17:59:17.246863       1 sidecar/probes.go:154] "healthz probe: can't connect to Scylla API" err="Get \"http://localhost/system/uptime_ms\": dial tcp 127.0.0.1:10000: connect: connection refused" Service="scylla/scylla-europe-west3-a-rack0-0"
E1210 17:59:17.942215       1 sidecar/controller.go:143] syncing key 'scylla/scylla-europe-west3-a-rack0-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp 127.0.0.1:10000: connect: connection refused
E1210 17:59:27.245980       1 sidecar/probes.go:154] "healthz probe: can't connect to Scylla API" err="Get \"http://localhost/system/uptime_ms\": dial tcp 127.0.0.1:10000: connect: connection refused" Service="scylla/scylla-europe-west3-a-rack0-0"
E1210 17:59:36.639323       1 sidecar/controller.go:143] syncing key 'scylla/scylla-europe-west3-a-rack0-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp 127.0.0.1:10000: connect: connection refused
E1210 17:59:37.246487       1 sidecar/probes.go:154] "healthz probe: can't connect to Scylla API" err="Get \"http://localhost/system/uptime_ms\": dial tcp 127.0.0.1:10000: connect: connection refused" Service="scylla/scylla-europe-west3-a-rack0-0"
```

and this is what it says on the operator 's logs:
```
I1210 17:58:13.304369       1 kubecrypto/certs.go:44] "Existing certificate template differs from the desired one" Secret="scylla/scylla-local-serving-certs" Diff=<
          &crypto.DesiredCertTemplate{
                ... // 9 identical fields
                DNSNames:       {"scylla-client.scylla.svc", "scylla-europe-west3-a-rack0-0.scylla.svc"},
                EmailAddresses: nil,
                IPAddresses: []net.IP{
        +               s"10.64.2.24",
                        s"10.68.14.85",
                },
                URIs:                        nil,
                PermittedDNSDomainsCritical: false,
                ... // 10 identical fields
          }
 >
I1210 17:58:13.304488       1 kubecrypto/certs.go:201] "Creating certificate" Secret="scylla/scylla-local-serving-certs" Reason="certificate needs an update"
I1210 17:58:13.590544       1 kubecrypto/certs.go:206] "Certificate created" Secret="scylla/scylla-local-serving-certs"
I1210 17:58:13.701686       1 record/event.go:307] "Event occurred" object="scylla/scylla-local-serving-certs" fieldPath="" kind="Secret" apiVersion="v1" type="Normal" reason="SecretUpdated" message="Secret scylla/scylla-local-serving-certs updated"
I1210 17:58:23.702170       1 scyllacluster/status.go:26] "Updating status" ScyllaCluster="scylla/scylla"
I1210 17:58:23.712618       1 scyllacluster/controller.go:257] "Hit conflict, will retry in a bit" Key="scylla/scylla" Error="Operation cannot be fulfilled on scyllaclusters.scylla.scylladb.com \"scylla\": the object has been modified; please apply your changes to the latest version and try again"
I1210 17:58:33.722006       1 scyllacluster/status.go:26] "Updating status" ScyllaCluster="scylla/scylla"
I1210 17:58:33.740175       1 scyllacluster/status.go:33] "Status updated" ScyllaCluster="scylla/scylla"
I1210 17:58:36.126573       1 record/event.go:307] "Event occurred" object="scylla/nodeconfig-podinfo-2bc1e768-1f18-4ca4-b61d-1df76f7272bf" fieldPath="" kind="ConfigMap" apiVersion="v1" type="Normal" reason="ConfigMapUpdated" message="ConfigMap scylla/nodeconfig-podinfo-2bc1e768-1f18-4ca4-b61d-1df76f7272bf updated"
```

### How can we reproduce it (as minimally and precisely as possible)?

1. Install cert-manager via the manifest you provided in the charts or with helm
2. Create the operator resource using helm and the values I provided
3. Create the cluster resource using helm and the values I provided at the beginning

### Scylla Operator version

CHART VERSION     v1.11.0
APP VERSION          1.11.0

### Kubernetes platform name and version

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.5-gke.200

### Please attach the must-gather archive.

na

**Comment by zimnx** [comment]
These resources are too low to run in non-developer mode. 
https://monitoring.docs.scylladb.com/stable/install/min-prod-hw.html
