### ISSUE TITLE
Unable to connect to API server

### ISSUE THREAD

**Issue by gibbonsjohnm** [scylladb/scylla-operator#172]
**Describe the bug**
After a single cluster node comes up, it cannot pass the readiness probe. Logs show a JSON error has occurred and that eventually it is unable to connect to Scylla API server.

**To Reproduce**
I believe this is specific to my setup, but 
1. Apply cert-manager.yaml
2. Apply operator.yaml
3. Wait for operator pod to come up.
4. Apply cluster.yaml

**Expected behavior**
3 cluster nodes to spin up and connect to the cluster successfully.

**Config Files**
Using current master config files with minimal changes (datacenter name, resource limits, etc.)

**Logs**
```2020-08-06T04:20:24.407303182Z 2020-08-06 04:20:24,407 INFO exited: scylla (terminated by SIGFPE (core dumped); not expected)
2020-08-06T04:20:24.956136863Z Traceback (most recent call last):
2020-08-06T04:20:24.956164264Z   File "/usr/lib/scylla/scylla-housekeeping", line 174, in <module>
2020-08-06T04:20:24.956169165Z     args.func(args)
2020-08-06T04:20:24.956172765Z   File "/usr/lib/scylla/scylla-housekeeping", line 101, in check_version
2020-08-06T04:20:24.956316074Z     current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
2020-08-06T04:20:24.956339376Z   File "/usr/lib/scylla/scylla-housekeeping", line 65, in get_api
2020-08-06T04:20:24.956345576Z     return get_json_from_url("http://" + api_address + path)
2020-08-06T04:20:24.956351177Z   File "/usr/lib/scylla/scylla-housekeeping", line 62, in get_json_from_url
2020-08-06T04:20:24.956356077Z     return json.loads(data.decode('utf-8'))
2020-08-06T04:20:24.956360677Z   File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
2020-08-06T04:20:24.956365578Z     return _default_decoder.decode(s)
2020-08-06T04:20:24.956370078Z   File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
2020-08-06T04:20:24.956375078Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2020-08-06T04:20:24.956379779Z   File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
2020-08-06T04:20:24.956447783Z     raise ValueError("No JSON object could be decoded")
2020-08-06T04:20:24.956458484Z ValueError: No JSON object could be decoded
```
```
2020-08-06T04:20:49.734352106Z E> Error while using detector GeronimoDetector: java.lang.IllegalStateException: Unable to connect to Scylla API server: java.net.ConnectException: Connection refused (Connection refused)
2020-08-06T04:20:49.734484515Z java.lang.IllegalStateException: Unable to connect to Scylla API server: java.net.ConnectException: Connection refused (Connection refused)
2020-08-06T04:20:49.734762433Z 	at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:191)
2020-08-06T04:20:49.734781335Z 	at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:196)
2020-08-06T04:20:49.734787535Z 	at com.scylladb.jmx.api.APIClient.getReader(APIClient.java:220)
2020-08-06T04:20:49.734794335Z 	at com.scylladb.jmx.api.APIClient.getJsonArray(APIClient.java:636)
2020-08-06T04:20:49.735000849Z 	at com.scylladb.jmx.api.APIClient.getJsonArray(APIClient.java:643)
2020-08-06T04:20:49.735817103Z 	at org.apache.cassandra.db.ColumnFamilyStore.checkRegistration(ColumnFamilyStore.java:107)
2020-08-06T04:20:49.735833004Z 	at com.scylladb.jmx.utils.APIMBeanServer.checkRegistrations(APIMBeanServer.java:299)
2020-08-06T04:20:49.735842805Z 	at com.scylladb.jmx.utils.APIMBeanServer.queryNames(APIMBeanServer.java:114)
2020-08-06T04:20:49.735846705Z 	at org.jolokia.backend.executor.AbstractMBeanServerExecutor.queryNames(AbstractMBeanServerExecutor.java:113)
2020-08-06T04:20:49.735850005Z 	at org.jolokia.detector.AbstractServerDetector.searchMBeans(AbstractServerDetector.java:46)
2020-08-06T04:20:49.735853305Z 	at org.jolokia.detector.AbstractServerDetector.getSingleStringAttribute(AbstractServerDetector.java:124)
2020-08-06T04:20:49.735856706Z 	at org.jolokia.detector.GeronimoDetector.detect(GeronimoDetector.java:32)
2020-08-06T04:20:49.735859806Z 	at org.jolokia.backend.MBeanServerHandler.detectServers(MBeanServerHandler.java:291)
2020-08-06T04:20:49.735863106Z 	at org.jolokia.backend.MBeanServerHandler.initServerHandle(MBeanServerHandler.java:138)
2020-08-06T04:20:49.735867406Z 	at org.jolokia.backend.MBeanServerHandler.<init>(MBeanServerHandler.java:76)
2020-08-06T04:20:49.735872307Z 	at org.jolokia.backend.LocalRequestDispatcher.<init>(LocalRequestDispatcher.java:72)
2020-08-06T04:20:49.735877107Z 	at org.jolokia.backend.BackendManager.init(BackendManager.java:330)
2020-08-06T04:20:49.735881607Z 	at org.jolokia.backend.BackendManager.access$100(BackendManager.java:51)
2020-08-06T04:20:49.735885607Z 	at org.jolokia.backend.BackendManager$Initializer.init(BackendManager.java:307)
2020-08-06T04:20:49.735890108Z 	at org.jolokia.backend.BackendManager.lazyInitIfNeeded(BackendManager.java:316)
2020-08-06T04:20:49.735894308Z 	at org.jolokia.backend.BackendManager.handleRequest(BackendManager.java:148)
2020-08-06T04:20:49.735898808Z 	at org.jolokia.http.HttpRequestHandler.executeRequest(HttpRequestHandler.java:197)
2020-08-06T04:20:49.735903409Z 	at org.jolokia.http.HttpRequestHandler.handlePostRequest(HttpRequestHandler.java:137)
2020-08-06T04:20:49.735907909Z 	at org.jolokia.jvmagent.handler.JolokiaHttpHandler.executePostRequest(JolokiaHttpHandler.java:290)
2020-08-06T04:20:49.73592461Z 	at org.jolokia.jvmagent.handler.JolokiaHttpHandler.doHandle(JolokiaHttpHandler.java:236)
2020-08-06T04:20:49.73592961Z 	at org.jolokia.jvmagent.handler.JolokiaHttpHandler.handle(JolokiaHttpHandler.java:178)
2020-08-06T04:20:49.735934511Z 	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
2020-08-06T04:20:49.735939111Z 	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
2020-08-06T04:20:49.735943511Z 	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
2020-08-06T04:20:49.736155125Z 	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
2020-08-06T04:20:49.736170426Z 	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
2020-08-06T04:20:49.736176127Z 	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
2020-08-06T04:20:49.736180727Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-08-06T04:20:49.736185327Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-08-06T04:20:49.736189728Z 	at java.lang.Thread.run(Thread.java:748)
```
```
2020-08-06T04:25:19.653008404Z {"L":"ERROR","T":"2020-08-06T04:25:19.652Z","M":"Readiness check failed","error":"Error while executing nodetool status in readiness check: unexpected end of JSON input","_trace_id":"Nx9OB4o-QjWG2rCKs_NTLg","S":"github.com/scylladb/scylla-operator/vendor/github.com/scylladb/go-log.Logger.log\n\t/go/src/github.com/scylladb/scylla-operator/vendor/github.com/scylladb/go-log/logger.go:92\ngithub.com/scylladb/scylla-operator/vendor/github.com/scylladb/go-log.Logger.Error\n\t/go/src/github.com/scylladb/scylla-operator/vendor/github.com/scylladb/go-log/logger.go:75\ngithub.com/scylladb/scylla-operator/pkg/sidecar.readinessCheck.func1\n\t/go/src/github.com/scylladb/scylla-operator/pkg/sidecar/checks.go:68\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2007\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2387\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1890"}
```

Mounting problem perhaps?

```
{"L":"INFO","T":"2020-08-06T04:49:00.558Z","M":"Setting up scylla.yaml","_trace_id":"DBQzrnqERByeKGNkK_XTzw"}
{"L":"INFO","T":"2020-08-06T04:49:00.558Z","M":"no scylla.yaml config map available"}
{"L":"INFO","T":"2020-08-06T04:49:00.560Z","M":"Setting up cassandra-rackdc.properties","_trace_id":"DBQzrnqERByeKGNkK_XTzw"}
{"L":"INFO","T":"2020-08-06T04:49:00.560Z","M":"unable to read properties","file":"/mnt/scylla-config/cassandra-rackdc.properties"}
```

**Environment:**
 - Platform:  AKS (Azure) + other kubeadm clusters
 - Kubernetes version: 1.16.8 + 1.16.10
 - Scylla version: 4.0.0
 - Scylla-operator version: 0.2.3

**Additional context**
Note, this suddenly starting happening today on a working cluster in a previous version of the operator (yanniszark/scylla-operator:v0.0-9e78183) as well. The errors above also occur on a brand new cluster and operator with the versions specified in the environment section.

**Comment by zimnx** [comment]
> Scylla version: 0.2.3

This seems invalid, there's no such version. Maybe you meant Operator?

Can you post output of `kubectl -n scylla describe pods` here?

**Comment by gibbonsjohnm** [comment]
Sorry, fixed the versions in my original post.

```
Name:         simple-cluster-us-east-1-us-east-1a-0
Namespace:    scylla
Priority:     0
Node:         aks-services-37428372-vmss000001/10.240.0.7
Start Time:   Thu, 06 Aug 2020 10:41:35 -0700
Labels:       app=scylla
              app.kubernetes.io/managed-by=scylla-operator
              app.kubernetes.io/name=scylla
              controller-revision-hash=simple-cluster-us-east-1-us-east-1a-cdd9d88c8
              scylla/cluster=simple-cluster
              scylla/datacenter=us-east-1
              scylla/rack=us-east-1a
              statefulset.kubernetes.io/pod-name=simple-cluster-us-east-1-us-east-1a-0
Annotations:  cni.projectcalico.org/podIP: 10.244.2.201/32
              prometheus.io/port: 9180
              prometheus.io/scrape: true
Status:       Running
IP:           10.244.2.201
IPs:
  IP:           10.244.2.201
Controlled By:  StatefulSet/simple-cluster-us-east-1-us-east-1a
Init Containers:
  sidecar-injection:
    Container ID:  docker://e250a3496431abf2bcc625b274b14b25a04469af01cb712b22f7496a6f0d399c
    Image:         scylladb/scylla-operator:v0.2.3
    Image ID:      docker-pullable://scylladb/scylla-operator@sha256:0b2927eaf0c162e5c71c6a5bf4f81e51262b766d3f354b652b7360327bb94c08
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      cp -a /scylla-operator /mnt/shared
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 06 Aug 2020 10:42:01 -0700
      Finished:     Thu, 06 Aug 2020 10:42:01 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  200M
    Requests:
      cpu:        1
      memory:     200M
    Environment:  <none>
    Mounts:
      /mnt/shared from shared (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from simple-cluster-member-token-rdrnn (ro)
Containers:
  scylla:
    Container ID:  docker://00de079e1aded87ba47ac5643d48754b2c854e3c9be1239ecc3e0ae8ade6925b
    Image:         scylladb/scylla:4.0.0
    Image ID:      docker-pullable://scylladb/scylla@sha256:b3f151598cc452aca4fba39a3f052d51f11cc597bd069adc0dbb41d37a57bb1d
    Ports:         7000/TCP, 7001/TCP, 7199/TCP, 9180/TCP, 9042/TCP, 9142/TCP, 9160/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      /mnt/shared/scylla-operator
      sidecar
    State:          Running
      Started:      Thu, 06 Aug 2020 10:42:02 -0700
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:      1
      memory:   1Gi
    Liveness:   http-get http://:8080/healthz delay=400s timeout=5s period=10s #success=1 #failure=3
    Readiness:  http-get http://:8080/readyz delay=30s timeout=5s period=10s #success=3 #failure=3
    Environment:
      POD_NAME:       simple-cluster-us-east-1-us-east-1a-0 (v1:metadata.name)
      POD_NAMESPACE:  scylla (v1:metadata.namespace)
      CPU:            1 (limits.cpu)
    Mounts:
      /mnt/scylla-client-config from scylla-client-config-volume (ro)
      /mnt/scylla-config from scylla-config-volume (ro)
      /mnt/shared from shared (ro)
      /var/lib/scylla from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from simple-cluster-member-token-rdrnn (ro)
  scylla-manager-agent:
    Container ID:  docker://ce09e6884fc3306d5d51e069f31a29e046414585ef996c7dd33b6a60dadd6bb4
    Image:         scylladb/scylla-manager-agent:2.0.2
    Image ID:      docker-pullable://scylladb/scylla-manager-agent@sha256:171e662cc5b036fc178e5acf44263316dab1e28a1ce4d0b8e745d9444fd72c0c
    Port:          10001/TCP
    Host Port:     0/TCP
    Args:
      -c
      /etc/scylla-manager-agent/scylla-manager-agent.yaml
      -c
      /mnt/scylla-agent-config/scylla-manager-agent.yaml
    State:          Running
      Started:      Thu, 06 Aug 2020 10:44:04 -0700
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 06 Aug 2020 10:42:03 -0700
      Finished:     Thu, 06 Aug 2020 10:44:04 -0700
    Ready:          True
    Restart Count:  1
    Limits:
      cpu:     1
      memory:  200M
    Requests:
      cpu:        1
      memory:     200M
    Environment:  <none>
    Mounts:
      /mnt/scylla-agent-config from scylla-agent-config-volume (ro)
      /var/lib/scylla from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from simple-cluster-member-token-rdrnn (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-simple-cluster-us-east-1-us-east-1a-0
    ReadOnly:   false
  shared:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  scylla-config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      scylla-config
    Optional:  true
  scylla-agent-config-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  scylla-agent-config-secret
    Optional:    true
  scylla-client-config-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  scylla-client-config-secret
    Optional:    true
  simple-cluster-member-token-rdrnn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  simple-cluster-member-token-rdrnn
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                  From                                       Message
  ----     ------                  ----                 ----                                       -------
  Warning  FailedScheduling        <unknown>            default-scheduler                          pod has unbound immediate PersistentVolumeClaims (repeated 4 times)
  Normal   Scheduled               <unknown>            default-scheduler                          Successfully assigned scylla/simple-cluster-us-east-1-us-east-1a-0 to aks-services-37428372-vmss000001
  Normal   SuccessfulAttachVolume  2m45s                attachdetach-controller                    AttachVolume.Attach succeeded for volume "pvc-48e23056-f8e1-4347-a4d6-bc78ce7939bb"
  Normal   Pulled                  2m30s                kubelet, aks-services-37428372-vmss000001  Container image "scylladb/scylla-operator:v0.2.3" already present on machine
  Normal   Created                 2m30s                kubelet, aks-services-37428372-vmss000001  Created container sidecar-injection
  Normal   Started                 2m30s                kubelet, aks-services-37428372-vmss000001  Started container sidecar-injection
  Normal   Pulled                  2m29s                kubelet, aks-services-37428372-vmss000001  Container image "scylladb/scylla:4.0.0" already present on machine
  Normal   Created                 2m29s                kubelet, aks-services-37428372-vmss000001  Created container scylla
  Normal   Started                 2m29s                kubelet, aks-services-37428372-vmss000001  Started container scylla
  Normal   Pulled                  27s (x2 over 2m29s)  kubelet, aks-services-37428372-vmss000001  Container image "scylladb/scylla-manager-agent:2.0.2" already present on machine
  Normal   Created                 27s (x2 over 2m29s)  kubelet, aks-services-37428372-vmss000001  Created container scylla-manager-agent
  Normal   Started                 27s (x2 over 2m28s)  kubelet, aks-services-37428372-vmss000001  Started container scylla-manager-agent
  Warning  Unhealthy               6s (x11 over 106s)   kubelet, aks-services-37428372-vmss000001  Readiness probe failed: Get http://10.244.2.201:8080/readyz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by gibbonsjohnm** [comment]
With developer mode turned off:

```
2020-08-06T19:53:39.219968818Z ERROR:root:['/var/lib/scylla/data'] did not pass validation tests, it may not be on XFS and/or has limited disk space.
2020-08-06T19:53:39.220001418Z This is a non-supported setup, and performance is expected to be very bad.
2020-08-06T19:53:39.220004418Z For better performance, placing your data on XFS-formatted directories is required.
2020-08-06T19:53:39.220007418Z To override this error, enable developer mode as follow:
2020-08-06T19:53:39.220009718Z sudo /opt/scylladb/scripts/scylla_dev_mode_setup --developer-mode 1
2020-08-06T19:53:39.220022918Z tuning /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/f8b3781b-1e82-4818-a1c3-63d806ec15bb/host3/target3:0:0/3:0:0:3/block/sdf
2020-08-06T19:53:39.220037919Z tuning: /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/f8b3781b-1e82-4818-a1c3-63d806ec15bb/host3/target3:0:0/3:0:0:3/block/sdf/queue/nomerges 2
2020-08-06T19:53:39.220041019Z warning: unable to tune /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/f8b3781b-1e82-4818-a1c3-63d806ec15bb/host3/target3:0:0/3:0:0:3/block/sdf/queue/nomerges to 2
```
