### ISSUE TITLE
Scylla container does not come up and ends up in crashloop state

### ISSUE THREAD

**Issue by cisse21** [scylladb/scylla-operator#2092]
### What happened?

The scylla container does not come up and ends up in a crashloopbackoff

### What did you expect to happen?

Scylla container to come up and be ready as soon as possible

### How can we reproduce it (as minimally and precisely as possible)?

deployed the operator and scylla cluster in an EKS setup using helm charts

### Scylla Operator version

https://github.com/scylladb/scylla-operator/releases/tag/v1.13.0

### Kubernetes platform name and version

<details>

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"29+", GitVersion:"v1.29.7-eks-2f46c53", GitCommit:"288383972a05cde5ed2c0daa913400d752313691", GitTreeState:"clean", BuildDate:"2024-07-25T04:23:15Z", GoVersion:"go1.22.5", Compiler:"gc", Platform:"linux/amd64"}

Kubernetes platform info:
Node - i4i.4xlarge
Volume - Node Volume
Deployed on EKS

### Please attach the must-gather archive.

```
Defaulted container "scylla" out of: scylla, scylladb-api-status-probe, scylla-manager-agent, sidecar-injection (init), sysctl-buddy (init)
I0826 07:06:16.171364       1 operator/cmd.go:21] maxprocs: Updating GOMAXPROCS=[14]: determined from CPU quota
I0826 07:06:16.171696       1 operator/sidecar.go:167] sidecar version "v1.13.0-rc.0-2-g7f37771"
I0826 07:06:16.171711       1 flag/flags.go:64] FLAG: --burst="5"
I0826 07:06:16.171716       1 flag/flags.go:64] FLAG: --clients-broadcast-address-type="ServiceClusterIP"
I0826 07:06:16.171719       1 flag/flags.go:64] FLAG: --cpu-count="14"
I0826 07:06:16.171721       1 flag/flags.go:64] FLAG: --external-seeds="[]"
I0826 07:06:16.171727       1 flag/flags.go:64] FLAG: --feature-gates="AllAlpha=false,AllBeta=false,AutomaticTLSCertificates=true"
I0826 07:06:16.171739       1 flag/flags.go:64] FLAG: --help="false"
I0826 07:06:16.171742       1 flag/flags.go:64] FLAG: --kubeconfig=""
I0826 07:06:16.171745       1 flag/flags.go:64] FLAG: --loglevel="2"
I0826 07:06:16.171747       1 flag/flags.go:64] FLAG: --namespace="scylla"
I0826 07:06:16.171749       1 flag/flags.go:64] FLAG: --nodes-broadcast-address-type="ServiceClusterIP"
I0826 07:06:16.171751       1 flag/flags.go:64] FLAG: --qps="2"
I0826 07:06:16.171754       1 flag/flags.go:64] FLAG: --service-name="scylla-us-east-1-us-east-1a-0"
I0826 07:06:16.171756       1 flag/flags.go:64] FLAG: --v="2"
I0826 07:06:16.172034       1 operator/sidecar.go:207] "Waiting for single service informer caches to sync"
I0826 07:06:16.177357       1 cache/reflector.go:351] Caches populated for *v1.Service from k8s.io/client-go@v0.29.5/tools/cache/reflector.go:229
I0826 07:06:16.272770       1 operator/sidecar.go:213] "Waiting for Service availability and IP address" Service="scylla/scylla-us-east-1-us-east-1a-0"
I0826 07:06:16.277605       1 cache/reflector.go:351] Caches populated for *v1.Service from k8s.io/client-go@v0.29.5/tools/cache/reflector.go:229
I0826 07:06:16.278681       1 operator/sidecar.go:236] "Waiting for Pod to have IP address assigned and scylla ContainerID set" Pod="scylla/scylla-us-east-1-us-east-1a-0"
I0826 07:06:16.284598       1 cache/reflector.go:351] Caches populated for *v1.Pod from k8s.io/client-go@v0.29.5/tools/cache/reflector.go:229
I0826 07:06:16.284720       1 operator/sidecar.go:286] "Waiting for NodeConfig's data ConfigMap " Selector="scylla-operator.scylladb.com/config-map-type=NodeConfigData,scylla-operator.scylladb.com/owner-uid=6241ef70-9c1e-4204-a5ef-3de76e404506"
I0826 07:06:16.288733       1 cache/reflector.go:351] Caches populated for *v1.ConfigMap from k8s.io/client-go@v0.29.5/tools/cache/reflector.go:229
I0826 07:06:16.289889       1 operator/sidecar.go:348] "Starting scylla"
I0826 07:06:16.289901       1 config/config.go:64] Setting up iotune cache
I0826 07:06:16.290011       1 config/config.go:315] Initialized IOTune benchmark cachepath/etc/scylla.d/io_properties.yamlcachePath/var/lib/scylla/io_properties.yaml
I0826 07:06:16.290019       1 config/config.go:69] Setting up scylla.yaml
I0826 07:06:16.290077       1 config/config.go:109] "no scylla.yaml config map available"
I0826 07:06:16.290835       1 config/config.go:74] Setting up cassandra-rackdc.properties
I0826 07:06:16.290851       1 config/config.go:156] "unable to read properties" file="/mnt/scylla-config/cassandra-rackdc.properties"
I0826 07:06:16.290926       1 config/config.go:79] Setting up entrypoint script
I0826 07:06:16.304129       1 config/config.go:258] "Scylla version detected" version={}
I0826 07:06:16.304164       1 config/config.go:287] "Scylla entrypoint" Command="/docker-entrypoint.py --listen-address=0.0.0.0 --seeds=10.100.217.87 --developer-mode=0 --overprovisioned=1 --smp=14 --prometheus-address=0.0.0.0 --broadcast-address=10.100.217.87 --broadcast-rpc-address=10.100.217.87"
I0826 07:06:16.304206       1 sidecar/controller.go:159] "Starting controller" Controller="SidecarController"
I0826 07:06:16.304221       1 cache/shared_informer.go:311] Waiting for caches to sync for SidecarController
I0826 07:06:16.304227       1 cache/shared_informer.go:318] Caches are synced for SidecarController
E0826 07:06:16.304891       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:06:16.305108       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:06:16.310638       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:06:16.331042       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:06:16.371475       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:06:16.452027       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '0'],)
E0826 07:06:16.612875       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
INFO  2024-08-26 07:06:16,917 seastar - Reactor backend: linux-aio
INFO  2024-08-26 07:06:16,921 [shard  0:n/a ] seastar - Perf-based stall detector creation failed (EACCESS), try setting /proc/sys/kernel/perf_event_paranoid to 1 or less to enable kernel backtraces: falling back to posix timer.
E0826 07:06:16.933813       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
INFO  2024-08-26 07:06:17,050 [shard  0:main] iotune - /var/lib/scylla/data passed sanity checks
WARN  2024-08-26 07:06:17,051 [shard  0:main] iotune - write_cache for /sys/devices/virtual/block/loop0/queue/write_cache is set to write back. Some disks have poor implementation of this mode, pay attention to the measurements accuracy.
INFO  2024-08-26 07:06:17,051 [shard  0:main] iotune - Disk parameters: max_iodepth=128 disks_per_array=1 minimum_io_size=512
Starting Evaluation. This may take a while...
E0826 07:06:17.575058       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:06:18.855968       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:06:21.418744       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:06:26.539440       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:06:36.780384       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:06:46.305183       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:06:57.261641       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:07:16.305308       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:07:46.305671       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:08:16.306103       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:08:19.183787       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:08:46.306657       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:09:16.307409       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
E0826 07:09:46.307528       1 sidecar/controller.go:143] syncing key 'scylla/scylla-us-east-1-us-east-1a-0' failed: can't sync the HostID annotation: can't get HostID: can't get local HostID: Get "http://localhost/storage_service/hostid/local": dial tcp [::1]:10000: connect: connection refused
I0826 07:09:50.715036       1 signals/signal.go:26] Received shutdown signal: terminated; shutting down...
I0826 07:09:50.715109       1 sidecar/controller.go:163] "Shutting down controller" Controller="SidecarController"
I0826 07:09:50.715122       1 operator/sidecar.go:377] "Waiting for scylla process to finish"
I0826 07:09:50.715109       1 operator/sidecar.go:393] "Sending SIGTERM to the scylla process"
I0826 07:09:50.715155       1 operator/sidecar.go:399] "Sent SIGTERM to the scylla process"
I0826 07:09:50.715186       1 sidecar/controller.go:166] "Shut down controller" Controller="SidecarController"
Measuring sequential write bandwidth: failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 27, in <module>
    setup.io()
  File "/scyllasetup.py", line 68, in io
    self._run(['/opt/scylladb/scripts/scylla_io_setup'])
  File "/scyllasetup.py", line 38, in _run
    subprocess.check_call(*args, **kwargs)
  File "/opt/scylladb/python3/lib64/python3.11/subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/python3/lib64/python3.11/subprocess.py", line 391, in call
    return p.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/python3/lib64/python3.11/subprocess.py", line 1264, in wait
    return self._wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/python3/lib64/python3.11/subprocess.py", line 2046, in _wait
    (pid, sts) = self._try_wait(0)
                 ^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/python3/lib64/python3.11/subprocess.py", line 2004, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/docker-entrypoint.py", line 17, in signal_handler
    supervisord.send_signal(signum)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'send_signal'
I0826 07:09:50.725551       1 operator/sidecar.go:384] "Scylla process finished"
```

### Anything else we need to know?

The pods start evaluation and takes forever to finish the evaluation, increasing the liveness and readiness probe of the statefulset to a pretty large number helps but this is not natively supported via ScyllaCluster CRD

**Comment by zimnx** [comment]
Please attach must-gather, we can't help without necessary information

**Comment by cisse21** [comment]
```
latest: Pulling from scylladb/scylla-operator
Digest: sha256:e38287506ce8605a1a8e0a1da8b8fce44fa008421f8908e0aa90685bff593c33
Status: Image is up to date for scylladb/scylla-operator:latest
I0826 09:48:37.898047       1 operator/gatherbase.go:116] "Created destination directory" Path="scylla-operator-must-gather-4zglglb7f4v5"
I0826 09:48:37.898137       1 operator/gatherbase.go:147] "Program info" Command="must-gather" Version="\"v1.14.0-alpha.0-129-g1fb54b6\""
I0826 09:48:37.899173       1 operator/mustgather.go:245] "Gathering artifacts" DestDir="scylla-operator-must-gather-4zglglb7f4v5"
I0826 09:48:44.728008       1 collect/collect.go:248] "Container doesn't yet have a status" Pod="scylla/scylla-us-east-1-us-east-1a-0" Container="sidecar-injection"
I0826 09:48:44.728038       1 collect/collect.go:248] "Container doesn't yet have a status" Pod="scylla/scylla-us-east-1-us-east-1a-0" Container="sysctl-buddy"
I0826 09:48:44.728044       1 collect/collect.go:248] "Container doesn't yet have a status" Pod="scylla/scylla-us-east-1-us-east-1a-0" Container="scylla"
I0826 09:48:44.728048       1 collect/collect.go:248] "Container doesn't yet have a status" Pod="scylla/scylla-us-east-1-us-east-1a-0" Container="scylladb-api-status-probe"
I0826 09:48:44.728062       1 collect/collect.go:248] "Container doesn't yet have a status" Pod="scylla/scylla-us-east-1-us-east-1a-0" Container="scylla-manager-agent"
I0826 09:49:18.014393       1 operator/mustgather.go:324] "Resource not found" Resource="/v1, Resource=namespaces"
I0826 09:49:39.030737       1 operator/mustgather.go:247] "Finished gathering artifacts" Duration="1m1.119250569s"
```

Getting this error and nothing on the `/workspace` folder any clue on how to proceed from here

**Comment by cisse21** [comment]
[Archive.zip](https://github.com/user-attachments/files/16748216/Archive.zip)
@zimnx Can you check the zip?
