### ISSUE TITLE
Minor/major upgrades endup in panic: "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#307]
**Describe the bug**

**To Reproduce**
1. Deploy scylla operator from scylladb/scylla-operator:nightly
2. Deploy scylla cluster of 3 nodes
3. Change scyllacluser/spec/version 
4. See the s-o logs

**Expected behavior**

**Config Files**
If relevant, upload your configuration files here using GitHub, there is no need to upload them to any 3rd party services

**Logs**

- db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/547cb5e1-cd10-4d9a-ad9a-18362a8736fd/20201222_093806/db-cluster-547cb5e1.zip  |
- monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/547cb5e1-cd10-4d9a-ad9a-18362a8736fd/20201222_093806/monitor-set-547cb5e1.zip |
- loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/547cb5e1-cd10-4d9a-ad9a-18362a8736fd/20201222_093806/loader-set-547cb5e1.zip  |
- kubernetes  | https://cloudius-jenkins-test.s3.amazonaws.com/547cb5e1-cd10-4d9a-ad9a-18362a8736fd/20201222_093806/kubernetes-547cb5e1.zip  |
- sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/547cb5e1-cd10-4d9a-ad9a-18362a8736fd/20201222_093806/sct-runner-547cb5e1.zip  

```
E1222 09:34:25.358920       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 344 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1a190a0, 0x2ea6630)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1a190a0, 0x2ea6630)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/scylladb/scylla-operator/pkg/controllers/cluster/actions.(*ClusterVersionUpgrade).Execute(0xc000c2e000, 0x1fccb20, 0xc000a86ab0, 0xc0009c80c0, 0x1fccb20, 0xc000a86ab0)
	/workspace/pkg/controllers/cluster/actions/upgrade_version.go:143 +0x8e
github.com/scylladb/scylla-operator/pkg/controllers/cluster.(*ClusterReconciler).sync(0xc000922000, 0xc0004c6240, 0x0, 0x0)
	/workspace/pkg/controllers/cluster/sync.go:72 +0xadc
github.com/scylladb/scylla-operator/pkg/controllers/cluster.(*ClusterReconciler).Reconcile(0xc000922000, 0xc00076bf48, 0x6, 0xc00076bf50, 0xb, 0xc000810998, 0x1f9bcc0, 0xc000810990, 0xc000561cb0)
	/workspace/pkg/controllers/cluster/cluster_controller.go:122 +0x7c7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00013c630, 0x1acfc00, 0xc000938b20, 0xc00043ee00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1/pkg/internal/controller/controller.go:233 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00013c630, 0x1d82e00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1/pkg/internal/controller/controller.go:209 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00013c630)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1/pkg/internal/controller/controller.go:188 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00080f900)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:155 +0x5e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00080f900, 0x1f87da0, 0xc000832a20, 0x1, 0xc0001e2d80)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00080f900, 0x3b9aca00, 0x0, 0x1, 0xc0001e2d80)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:133 +0xaa
k8s.io/apimachinery/pkg/util/wait.Until(0xc00080f900, 0x3b9aca00, 0xc0001e2d80)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.4/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.1/pkg/internal/controller/controller.go:170 +0x431
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1747cfe]
```
**Environment:**
 - Platform: GKE
 - Kubernetes version: 1.15
 - Scylla version: 4.2.0
 - Scylla-operator version: nightly

**Comment by dkropachev** [comment]
Most likely it is due to the lack of genericUpgrade in cluster spec.

**Comment by dkropachev** [comment]
Here we have two issues:

1. s-o tightly depending on CRD while having no CRD version control.
2. sct having outdated CRD

**Comment by dkropachev** [comment]
Created separate s-o feature request https://github.com/scylladb/scylla-operator/issues/311
