### ISSUE TITLE
The eks cluster exposes ports to services by configuring a nodeport service. Services cannot call the addresses of eks

### ISSUE THREAD

**Issue by woshihahaha** [scylladb/scylla-operator#588]
### The following error occurs when the hugegraph logs are started:
信息: Started listener bound to [0.0.0.0:8080]
2021-05-07 16:27:43 5725  [main] [INFO ] com.baidu.hugegraph.server.RestServer [] - Graph 'hugegraph' was successfully configured via 'conf/hugegraph.properties'
2021-05-07 16:27:48 11437 [cluster1-nio-worker-2] [WARN ] com.datastax.driver.core.HostConnectionPool [] - Error creating connection to /10.100.116.155:30942
com.datastax.driver.core.exceptions.TransportException: [/10.100.116.155:30942] Cannot connect
        at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:224) [cassandra-driver-core-3.6.0.jar:?]
        at com.datastax.driver.core.Connection$1.operationComplete(Connection.java:194) [cassandra-driver-core-3.6.0.jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507) [netty-all-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500) [netty-all-4.1.13.Final.jar:4.1.13.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479) [netty-all-4.1.13.Final.jar:4.1.13.Final]

- Platform:  EKS
- Kubernetes version: v1.19.0
- Scylla version: scylladb/scylla:4.2.0
- Scylla-operator version:1.1.0

**Comment by tnozicka** [comment]
Closing as stale. If you are still having troubles, please file a new issue on a supported version.
