### ISSUE TITLE
Missing scyllaAgentConfig in examples/gke/cluster.yaml + /var/lib/scylla/commitlog was not found

### ISSUE THREAD

**Issue by akhilles** [scylladb/scylla-operator#87]
**Describe the bug**
Fails to create cluster:
```
namespace/scylla created
clusterrole.rbac.authorization.k8s.io/scylla-cluster-member created
serviceaccount/scylla-cluster-member created
clusterrolebinding.rbac.authorization.k8s.io/scylla-cluster-member created
The Cluster "scylla-cluster" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"scylla.scylladb.com/v1alpha1", "kind":"Cluster", "metadata":map[string]interface {}{"annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"scylla.scylladb.com/v1alpha1\",\"kind\":\"Cluster\",\"metadata\":{\"annotations\":{},\"labels\":{\"controller-tools.k8s.io\":\"1.0\"},\"name\":\"scylla-cluster\",\"namespace\":\"scylla\"},\"spec\":{\"agentVersion\":\"2.0.2\",\"cpuset\":true,\"datacenter\":{\"name\":\"us-west1-b\",\"racks\":[{\"members\":2,\"name\":\"us-west1\",\"placement\":{\"nodeAffinity\":{\"requiredDuringSchedulingIgnoredDuringExecution\":{\"nodeSelectorTerms\":[{\"matchExpressions\":[{\"key\":\"failure-domain.beta.kubernetes.io/zone\",\"operator\":\"In\",\"values\":[\"us-west1-b\"]}]}]}},\"tolerations\":[{\"effect\":\"NoSchedule\",\"key\":\"role\",\"operator\":\"Equal\",\"value\":\"scylla-clusters\"}]},\"resources\":{\"limits\":{\"cpu\":30,\"memory\":\"115G\"}},\"scyllaConfig\":\"scylla-config\",\"storage\":{\"capacity\":\"2995G\",\"storageClassName\":\"local-raid-disks\"}}]},\"version\":\"3.2.1\"}}\n"}, "creationTimestamp":"2020-05-15T19:27:57Z", "generation":1, "labels":map[string]interface {}{"controller-tools.k8s.io":"1.0"}, "name":"scylla-cluster", "namespace":"scylla", "uid":"8b4b3b60-d4b6-40ec-a8aa-047ec88c5dce"}, "spec":map[string]interface {}{"agentVersion":"2.0.2", "cpuset":true, "datacenter":map[string]interface {}{"name":"us-west1-b", "racks":[]interface {}{map[string]interface {}{"members":2, "name":"us-west1", "placement":map[string]interface {}{"nodeAffinity":map[string]interface {}{"requiredDuringSchedulingIgnoredDuringExecution":map[string]interface {}{"nodeSelectorTerms":[]interface {}{map[string]interface {}{"matchExpressions":[]interface {}{map[string]interface {}{"key":"failure-domain.beta.kubernetes.io/zone", "operator":"In", "values":[]interface {}{"us-west1-b"}}}}}}}, "tolerations":[]interface {}{map[string]interface {}{"effect":"NoSchedule", "key":"role", "operator":"Equal", "value":"scylla-clusters"}}}, "resources":map[string]interface {}{"limits":map[string]interface {}{"cpu":30, "memory":"115G"}}, "scyllaConfig":"scylla-config", "storage":map[string]interface {}{"capacity":"2995G", "storageClassName":"local-raid-disks"}}}}, "version":"3.2.1"}}: validation failure list:
spec.datacenter.racks.scyllaAgentConfig in body is required
```

**To Reproduce**
1. Follow the guide at https://github.com/scylladb/scylla-operator/blob/master/docs/gke.md

**Environment:**
 - Platform: GKE
 - Kubernetes version: v1.15.11-gke.3
 - Scylla-operator version: master

**Comment by akhilles** [comment]
Tried adding `scyllaAgentConfig: "scylla-agent-config"` to `cluster.yaml` but cluster pods are stuck in pending:

```
$ kubectl describe -n scylla pod scylla-cluster-us-west1-b-us-west1-0

...
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  33s (x9 over 9m20s)  default-scheduler  0/6 nodes are available: 1 Insufficient cpu, 1 Insufficient memory, 2 node(s) had taints that the pod didn't tolerate, 3 node(s) didn't find available persistent volumes to bind.
```

**Comment by akhilles** [comment]
Tried using the `gke.sh` script this time (after adding `scyllaAgentConfig: "scylla-agent-config"` to `cluster.yaml`) and deployment still failed:

```
$ kubectl logs -n scylla scylla-cluster-us-west1-b-us-west1-0 -c scylla
{"L":"INFO","T":"2020-05-15T22:21:38.112Z","M":"sidecar started","version":"0.1.6","build_date":"2020-04-30T08:16:18Z","commit":"9858a394f3f771a28f9cfe829a9a85e33ba0d4d3","built_by":"goreleaser","go_version":"go version go1.14.2 linux/amd64","options":{"Name":"scylla-cluster-us-west1-b-us-west1-0","Namespace":"scylla","LogLevel":"info","CPU":"30"},"_trace_id":"sRQvJFRvQl2Pk774U0NbEQ"}
{"L":"INFO","T":"2020-05-15T22:21:38.236Z","M":"Registering Components.","_trace_id":"sRQvJFRvQl2Pk774U0NbEQ"}
{"L":"INFO","T":"2020-05-15T22:21:38.252Z","M":"Member loaded","member":{"Name":"scylla-cluster-us-west1-b-us-west1-0","Namespace":"scylla","IP":"10.72.2.5","StaticIP":"10.75.244.137","Rack":"us-west1","Datacenter":"us-west1-b","Cluster":"scylla-cluster"},"_trace_id":"N7p5pr29T_m4P4DhhDL2bA"}
{"L":"INFO","T":"2020-05-15T22:21:38.350Z","N":"member_controller","M":"Setting up HTTP Checks...","_trace_id":"N7p5pr29T_m4P4DhhDL2bA"}
{"L":"INFO","T":"2020-05-15T22:21:38.350Z","N":"member_controller","M":"Setting up config files","_trace_id":"N7p5pr29T_m4P4DhhDL2bA"}
{"L":"INFO","T":"2020-05-15T22:21:38.350Z","N":"member_controller","M":"Setting up scylla.yaml","_trace_id":"N7p5pr29T_m4P4DhhDL2bA"}
{"L":"INFO","T":"2020-05-15T22:21:38.350Z","N":"member_controller","M":"no scylla.yaml config map available"}
{"L":"INFO","T":"2020-05-15T22:21:38.352Z","N":"member_controller","M":"Setting up cassandra-rackdc.properties","_trace_id":"N7p5pr29T_m4P4DhhDL2bA"}
{"L":"INFO","T":"2020-05-15T22:21:38.352Z","N":"member_controller","M":"unable to read properties","file":"/mnt/scylla-config/cassandra-rackdc.properties"}
{"L":"INFO","T":"2020-05-15T22:21:38.352Z","N":"member_controller","M":"Setting up entrypoint script","_trace_id":"N7p5pr29T_m4P4DhhDL2bA"}
{"L":"INFO","T":"2020-05-15T22:21:38.361Z","N":"member_controller","M":"Scylla entrypoint","command":"/docker-entrypoint.py --listen-address=10.72.2.5 --broadcast-address=10.75.244.137 --broadcast-rpc-address=10.75.244.137 --seeds=10.75.244.137 --developer-mode=0 --smp=30 --cpuset=0-31","_trace_id":"N7p5pr29T_m4P4DhhDL2bA"}
{"L":"INFO","T":"2020-05-15T22:21:38.361Z","N":"member_controller","M":"Starting the scylla process","_trace_id":"N7p5pr29T_m4P4DhhDL2bA"}
{"L":"INFO","T":"2020-05-15T22:21:38.362Z","M":"Starting the sidecar...","_trace_id":"sRQvJFRvQl2Pk774U0NbEQ"}
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '0'],)
running: (['/opt/scylladb/scripts/scylla_cpuset_setup', '--cpuset', '0-31'],)
{"L":"INFO","T":"2020-05-15T22:21:38.576Z","N":"member_controller","M":"Starting reconciliation...","_trace_id":"oBAX8BCHSIykZPkPIns-4w"}
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
ERROR:root:/var/lib/scylla/commitlog was not found. Please check the configuration and run scylla_io_setup again.

tuning /sys/devices/virtual/block/md0
tuning: /sys/devices/virtual/block/md0/queue/nomerges 2
warning: unable to tune /sys/devices/virtual/block/md0/queue/nomerges to 2

tuning /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:5/1:0:5:0/block/sdf
tuning: /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:5/1:0:5:0/block/sdf/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:5/1:0:5:0/block/sdf/queue/nomerges to 2

tuning /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:3/1:0:3:0/block/sdd
tuning: /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:3/1:0:3:0/block/sdd/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:3/1:0:3:0/block/sdd/queue/nomerges to 2

tuning /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:1/1:0:1:0/block/sdb
tuning: /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:1/1:0:1:0/block/sdb/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:1/1:0:1:0/block/sdb/queue/nomerges to 2

tuning /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:8/1:0:8:0/block/sdi
tuning: /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:8/1:0:8:0/block/sdi/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:8/1:0:8:0/block/sdi/queue/nomerges to 2

tuning /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:6/1:0:6:0/block/sdg
tuning: /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:6/1:0:6:0/block/sdg/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:6/1:0:6:0/block/sdg/queue/nomerges to 2

tuning /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:4/1:0:4:0/block/sde
tuning: /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:4/1:0:4:0/block/sde/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:4/1:0:4:0/block/sde/queue/nomerges to 2

tuning /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:2/1:0:2:0/block/sdc
tuning: /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:2/1:0:2:0/block/sdc/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:2/1:0:2:0/block/sdc/queue/nomerges to 2

tuning /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:7/1:0:7:0/block/sdh
tuning: /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:7/1:0:7:0/block/sdh/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:04.0/virtio1/host1/target1:0:7/1:0:7:0/block/sdh/queue/nomerges to 2

failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 17, in <module>
    setup.io()
  File "/scyllasetup.py", line 53, in io
    self._run(['/opt/scylladb/scripts/scylla_io_setup'])
  File "/scyllasetup.py", line 32, in _run
    subprocess.check_call(*args, **kwargs)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_io_setup']' returned non-zero exit status 1.
{"L":"INFO","T":"2020-05-15T22:22:08.469Z","N":"member_controller","M":"Starting reconciliation...","_trace_id":"O-E9qSQkT76KP5JrCG41iQ"}
{"L":"INFO","T":"2020-05-15T22:22:15.260Z","N":"member_controller.scylla_client","M":"HTTP retry backoff","operation":"StorageServiceHostIdGet","wait":"1.176203636s","error":"dial tcp 10.72.2.5:10001: connect: connection refused"}
...
```

**Comment by dahankzter** [comment]
This last error I remember seeing only for certain versions of scylla actually. Perhaps you can try another version?

**Comment by akhilles** [comment]
Upgrading to scylla 4.0 seems to have fixed it. I opened #88 to merge this change.
