### ISSUE TITLE
Use stable image for eks node setup

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#893]
EKS examples use a temporary image `scylladb/scylla-machine-image:k8s-aws-666.development-20201023.0c4dfa1` which is not great. We should migrate to a stable tag.

**Comment by mykaul** [comment]
This looks important, I'd be happy to see it prioritized.

**Comment by tnozicka** [comment]
to add to it @vponomaryov has found out that it broke, rather permanently because scylladb rpm repo for 4.1 got pruned
```
failure: repodata/repomd.xml from scylla: [Errno 256] No more mirrors to try.
http://downloads.scylladb.com/rpm/unstable/centos/branch-4.1/2020-08-31T00:50:11Z/scylla/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_ntp_setup", line 93, in <module>
    run('yum install -y ntp ntpdate')
  File "/opt/scylladb/scripts/scylla_util.py", line 340, in run
    return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr, env=scylla_env)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['yum', 'install', '-y', 'ntp', 'ntpdate']' returned non-zero exit status 1.
NTP setup failed.
Traceback (most recent call last):
  File "/opt/scylladb/scylla-machine-image/scylla_k8s_node_setup", line 61, in <module>
    run('/opt/scylladb/scripts/scylla_setup --no-coredump-setup --no-sysconfig-setup --no-raid-setup --no-io-setup --no-bootparam-setup --no-ec2-check --no-cpuscaling-setup --no-kernel-check --no-verify-package --no-enable-service --no-selinux-setup --no-version-check --no-node-exporter')
  File "/opt/scylladb/scripts/scylla_util.py", line 340, in run
    return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr, env=scylla_env)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_setup', '--no-coredump-setup', '--no-sysconfig-setup', '--no-raid-setup', '--no-io-setup', '--no-bootparam-setup', '--no-ec2-check', '--no-cpuscaling-setup', '--no-kernel-check', '--no-verify-package', '--no-enable-service', '--no-selinux-setup', '--no-version-check', '--no-node-exporter']' returned non-zero exit status 1.
```

@zimnx I think you've built it last time, can we build an equivalent image from our repo?

**Comment by tnozicka** [comment]
most of this (maybe all) will be replaced by the new storage setup API so I am fine with any hot fix to get us at least a new image with nicer tag for the interim

**Comment by mykaul** [comment]
4.1?!

**Comment by tnozicka** [comment]
yeah :( this is the historic setup that we are now replacing but we need to cover the interim for operator users

**Comment by tnozicka** [comment]
for xref, we are tracking the breakage in https://github.com/scylladb/scylla-operator/issues/1218. I assume when the fix will be getting released we'll fix this one as well and give it a proper tag. Long term, we'll deprecate this (https://github.com/scylladb/scylla-operator/issues/1219) and move everyone to storage setup APIs or let them set it up on their own.

**Comment by tnozicka** [comment]
fixed in https://github.com/scylladb/scylla-operator/pull/1221
