### ISSUE TITLE
Unable to create scylla cluster with operator

### ISSUE THREAD

**Issue by vanlueckn** [scylladb/scylla-operator#972]
**To Reproduce**
1. Create Operator 
2. Create cluster via CRD
3. See error

**Expected behavior**

**Config Files**
Cluster CRD
```yaml
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: stoffi-cluster
  namespace: scylla
spec:
  version: 2.3.1
  repository: scylladb/scylla
  developerMode: true
  cpuset: false
  automaticOrphanedNodeCleanup: true
  datacenter:
    name: eu-west-1
    racks:
      - name: eu-west-1a
        members: 3
        storage:
          capacity: 50G
          storageClassName: local-path
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 4
            memory: 8Gi
        placement:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: failure-domain.beta.kubernetes.io/region
                    operator: In
                    values:
                      - eu-west-1
                  - key: failure-domain.beta.kubernetes.io/zone
                    operator: In
                    values:
                      - eu-west-1a
          tolerations:
            - key: role
              operator: Equal
              value: scylla-clusters
              effect: NoSchedule
```

**Logs**

```
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 11, in <module>
    arguments = commandlineparser.parse()
  File "/commandlineparser.py", line 21, in parse
    return parser.parse_args()
  File "/usr/lib64/python3.4/argparse.py", line 1731, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib64/python3.4/argparse.py", line 2386, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib64/python3.4/argparse.py", line 2373, in exit
    _sys.exit(status)
SystemExit: 2
usage: docker-entrypoint.py [-h] [--developer-mode {0,1}]
                            [--experimental {0,1}] [--seeds SEEDS]
                            [--cpuset CPUSET] [--smp SMP] [--memory MEMORY]
                            [--overprovisioned {0,1}]
                            [--listen-address LISTENADDRESS]
                            [--broadcast-address BROADCASTADDRESS]
                            [--broadcast-rpc-address BROADCASTRPCADDRESS]
                            [--api-address APIADDRESS]
                            [--disable-version-check]
                            [--authenticator AUTHENTICATOR]
                            [--authorizer AUTHORIZER]
docker-entrypoint.py: error: unrecognized arguments: --prometheus-address=0.0.0.0
E0416 20:57:43.534596       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 20:57:53.534195       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 20:58:03.534934       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 20:58:13.534407       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 20:58:23.534916       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 20:58:33.534965       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 20:58:43.533951       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 20:58:53.534647       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 20:59:03.534494       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 20:59:13.534370       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 20:59:23.534975       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 20:59:33.534537       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 20:59:43.534952       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 20:59:53.533916       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 21:00:03.535172       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 21:00:13.534521       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 21:00:23.534651       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 21:00:33.534487       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Service="scylla/stoffi-cluster-eu-west-1-eu-west-1a-0"
E0416 21:00:43.534547       1 sidecar/probes.go:152] "healthz probe: can't connect to Scylla API" err="dial tcp [::1]:10000: connect: connection refused" Ser
```
**Environment:**
 - Platform:  Debian 11
 - Kubernetes version: K3S 1.22
 - Scylla version: latest
 - Scylla-operator version: latest

**Comment by tnozicka** [comment]
scylla-operator requires scylla `>=4.3`, while you are using `2.3.1`.

see https://github.com/scylladb/scylla-operator/blob/master/docs/source/releases.md#support-matrix

Please try a supported version.
