### ISSUE TITLE
EKS tuning DaemonSet no longer works with the provided yaml

### ISSUE THREAD

**Issue by PenguinToast** [scylladb/scylla-operator#986]
**Describe the bug**
The EKS setup docs instruct people to apply node-setup-daemonset.yaml: https://operator.docs.scylladb.com/stable/eks.html#install-the-local-provisioner

However, this currently results in the tuning daemonset erroring with `error: subprocess.CalledProcessError: Command '['pidof', '-s', 'irqbalance']' returned non-zero exit status 1.`

I was recommended in Slack to change the `--all` flag to `--setup-disks` and use experimental optimizations from operator documentation: https://scylladb-users.slack.com/archives/C2NLNBXLN/p1654652056648269

However, this just results in the tuning image logging only `No disks found`.

**To Reproduce**
1. Follow EKS setup instructions up to "Deploy tuning DaemonSet"
2. Apply the tuning daemonset yaml
3. Observe errors in the logs

**Expected behavior**
The tuning daemonset should either not error when run with `--all`, or it should fine disks when run with `--setup-disks`.

**Logs**
Full logs:
```
/bin/sh: sudo: command not found
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: download.cf.centos.org
 * epel: d2lzkl7pfhq30w.cloudfront.net
 * extras: download.cf.centos.org
 * updates: download.cf.centos.org
http://mirror.es.its.nyu.edu/epel/7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on http://mirror.es.its.nyu.edu/epel/7/x86_64/repodata/repomd.xml: (28, 'Connection timed out after 30001 milliseconds')
Trying other mirror.
Resolving Dependencies
--> Running transaction check
---> Package ntp.x86_64 0:4.2.6p5-29.el7.centos.2 will be installed
--> Processing Dependency: libopts.so.25()(64bit) for package: ntp-4.2.6p5-29.el7.centos.2.x86_64
---> Package ntpdate.x86_64 0:4.2.6p5-29.el7.centos.2 will be installed
--> Running transaction check
---> Package autogen-libopts.x86_64 0:5.18-5.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package              Arch        Version                       Repository
                                                                           Size
================================================================================
Installing:
 ntp                  x86_64      4.2.6p5-29.el7.centos.2       base      549 k
 ntpdate              x86_64      4.2.6p5-29.el7.centos.2       base       87 k
Installing for dependencies:
 autogen-libopts      x86_64      5.18-5.el7                    base       66 k

Transaction Summary
================================================================================
Install  2 Packages (+1 Dependent package)

Total download size: 701 k
Installed size: 1.6 M
Downloading packages:
--------------------------------------------------------------------------------
Total                                              2.5 MB/s | 701 kB  00:00     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : autogen-libopts-5.18-5.el7.x86_64                            1/3 
  Installing : ntpdate-4.2.6p5-29.el7.centos.2.x86_64                       2/3 
  Installing : ntp-4.2.6p5-29.el7.centos.2.x86_64                           3/3 
  Verifying  : ntpdate-4.2.6p5-29.el7.centos.2.x86_64                       1/3 
  Verifying  : ntp-4.2.6p5-29.el7.centos.2.x86_64                           2/3 
  Verifying  : autogen-libopts-5.18-5.el7.x86_64                            3/3 

Installed:
  ntp.x86_64 0:4.2.6p5-29.el7.centos.2 ntpdate.x86_64 0:4.2.6p5-29.el7.centos.2

Dependency Installed:
  autogen-libopts.x86_64 0:5.18-5.el7                                           

Complete!
 8 Jun 01:27:23 ntpdate[41241]: adjust time server 65.100.46.166 offset 0.000245 sec
[1;31mNo swap is configured, it is highly recommended to setup swap on Scylla node.[0m
ScyllaDB setup finished.
No disks found
irqbalance is not running
Setting a physical interface eth0...
Distributing all IRQs
Setting mask 00000001 in /proc/irq/93/smp_affinity
Setting mask 00000001 in /proc/irq/94/smp_affinity
Setting mask 00000001 in /proc/irq/95/smp_affinity
Setting mask 00000001 in /proc/irq/92/smp_affinity
Setting mask 0000000e in /sys/class/net/eth0/queues/rx-3/rps_cpus
Setting mask 0000000e in /sys/class/net/eth0/queues/rx-1/rps_cpus
Setting mask 0000000e in /sys/class/net/eth0/queues/rx-2/rps_cpus
Setting mask 0000000e in /sys/class/net/eth0/queues/rx-0/rps_cpus
Setting net.core.rps_sock_flow_entries to 32768
Setting limit 8192 in /sys/class/net/eth0/queues/rx-3/rps_flow_cnt
Setting limit 8192 in /sys/class/net/eth0/queues/rx-1/rps_flow_cnt
Setting limit 8192 in /sys/class/net/eth0/queues/rx-2/rps_flow_cnt
Setting limit 8192 in /sys/class/net/eth0/queues/rx-0/rps_flow_cnt
Trying to enable ntuple filtering HW offload for eth0...not supported
Setting mask 00000001 in /sys/class/net/eth0/queues/tx-2/xps_cpus
Setting mask 00000004 in /sys/class/net/eth0/queues/tx-0/xps_cpus
Setting mask 00000002 in /sys/class/net/eth0/queues/tx-3/xps_cpus
Setting mask 00000008 in /sys/class/net/eth0/queues/tx-1/xps_cpus
Writing '4096' to /proc/sys/net/core/somaxconn
Writing '4096' to /proc/sys/net/ipv4/tcp_max_syn_backlog
Traceback (most recent call last):
  File "/opt/scylladb/scylla-machine-image/scylla_k8s_node_setup", line 71, in <module>
    os.kill(get_pid("irqbalance"), signal.SIGHUP)
  File "/opt/scylladb/scylla-machine-image/scylla_k8s_node_setup", line 37, in get_pid
    return int(check_output(["pidof","-s",name]))
  File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pidof', '-s', 'irqbalance']' returned non-zero exit status 1.
```

**Environment:**
 - Platform: EKS w/ Bottlerocket nodes
 - Kubernetes version: 1.19
 - Scylla-operator version: e.g.: master

**Comment by tnozicka** [comment]
Closing as stale. If you are still having troubles, please file a new issue on a supported version.
